backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: "quotes"
    label: "Cytaty"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Cytat", name: "quote", widget: "text" }

  - name: "home"
    label: "Strona główna"
    folder: "content/home"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Sekcja pierwsza - tytuł",
          name: "section1Title",
          widget: "string",
        }
      - {
          label: "Sekcja pierwsza - treść",
          name: "section1Text",
          widget: "string",
        }
      - {
          label: "Sekcja druga - tytuł",
          name: "section2Title",
          widget: "string",
        }
      - {
          label: "Sekcja druga - treść",
          name: "section2Text",
          widget: "string",
        }

  - name: "news"
    label: "Aktualności"
    folder: "content/news/simple"
    create: false
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Tytuł", widget: "string" }
      - {
          name: "itemsPerPage",
          label: "Ilość wpisów na jednej stronie",
          widget: "string",
        }
      - {
          name: "body",
          label: "Treść sekcji 'Aktualności'",
          widget: "rich-text",
        }

  - name: "post"
    label: "Nowy wpis"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "title", label: "Tytuł wpisu", widget: "string" }
      - { name: "body", label: "Treść wpisu", widget: "rich-text" }
      - {
          name: "images",
          label: "Zdjęcia",
          widget: "list",
          allow_add: true,
          field: { label: "Obrazek", name: "image", widget: "image" },
        }

  - name: "about"
    label: "O nas"
    folder: "content/o-nas"
    create: false
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Tytuł", widget: "string" }
      - { name: "body", label: "Treść sekcji 'O nas'", widget: "rich-text" }

  - name: "contact"
    label: "Kontakt"
    folder: "content/contact"
    create: false
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Tytuł", widget: "string" }
      - { name: "body", label: "Treść sekcji 'Kontakt'", widget: "rich-text" }

  - name: "before-you-buy"
    label: "Zanim kupisz"
    folder: "content/before-you-buy"
    create: false
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Tytuł", widget: "string" }
      - {
          name: "body",
          label: "Treść sekcji 'Zanim kupisz'",
          widget: "rich-text",
        }
